### ISSUE TITLE
Provide example of Lambda without Laconia

### ISSUE THREAD

**Issue by chris-kobrzak** [nearst/laconia#247]
**Is your feature request related to a problem? Please describe.**
As someone who is quite new to AWS Lambda, I would find it quite beneficial to be able to see a comparison of code snippets with and without Laconia.

**Describe the solution you'd like [optional]**
The current [basic example](https://laconiajs.io/docs/introduction/getting-started#basic-example) jumps straight at a Laconia usage example but I think it would be a great selling point to go: look, this is how convoluted the code gets when you try to manage the dependencies manually and here's an elegant solution that Laconia provides.

Greetings from 33 Holborn 👋

**Comment by ceilfors** [comment]
Thanks for the suggestion @chris-kobrzak, how I have missed 33 Holborn!

That's a good idea. I'm thinking that it should be in a blog, article, or laconia main home page. It's poorly marketed at the moment.. The getting started document is targetting people who are getting ready to get started i.e. they are already sold with the concept. Would you be interested to a blog?

**Comment by geoffdutton** [comment]
I added a very simple comparison of with and without Laconia [here](https://github.com/geoffs-uncategorized-forks/laconiajs-examples/tree/sls-vanilla-update/examples/serverless-vanilla#comparison-with-and-without-laconiajs).
