### ISSUE TITLE
Create maintainers document

### ISSUE THREAD

**Issue by ceilfors** [nearst/laconia#525]
The problems I'm seeing at the moment:
- It is not immediately obvious who is the maintainers of this repository. We'd like this to be more visible to the community.
- It is not clear who should merge the PR when a PR is merged by maintainers. It can be a frustrating experience for maintainers when a PR is not visited right away.

I quite like and influenced by [Pieter Hintjens' C4](https://rfc.zeromq.org/spec:22/C4/), but I'm also conscious that the document might get too comprehensive for a still small community like laconia. For example, I love this idea from C4:

> - Maintainers SHOULD NOT merge their own patches except in exceptional cases, such as non-responsiveness from other Maintainers for an extended period (more than 1-2 days)
> - A new Contributor who makes a correct patch SHALL be invited to become a Maintainer

I personally don't have an extensive experience maintaining an open-source project, thoughts @hugosenari @geoffdutton @sakthivel-tw?

**Comment by geoffdutton** [comment]
I don't really have any experience either, but maintainers not merging their own patches makes sense to me.

I'd suggest we utilize the "request review" feature too.
