### ISSUE TITLE
Transfer infrastructure ownership to NearSt

### ISSUE THREAD

**Issue by ceilfors** [nearst/laconia#915]
Following the discussion: https://github.com/laconiajs/laconia/discussions/913.

Infra to be transferred:

- [x] GitHub org
   - [x] laconia
   - [x] website (documentation)
   - [x] examples
- [x] NPM publish permission
- [x] Documentation website
   - [x] Transfer Domain ownership
   - [x] Transfer Hosted zone
- [x] Test NearSt can run their own acceptance test from their local machine
- [x] CircleCI

**Comment by ceilfors** [comment]
@mpxr @tschoffelen Hitting the following error when transferring GitHub org.

<img width="718" alt="image" src="https://github.com/laconiajs/laconia/assets/1336981/d1f711ec-8ab6-463e-a22e-5d946b29fc05">

**Comment by ceilfors** [comment]
@mpxr I have modified the registrant contact by using NearSt address and your contact details, i.e. your NearSt email address and phone number.

Please check if you received any email from ICANN and approve that change, as the Transfer out operation is currently blocked due to that.

<img width="581" alt="image" src="https://github.com/laconiajs/laconia/assets/1336981/45bfae9b-7050-489e-98a4-7ffc2143a3df">

**Comment by tschoffelen** [comment]
> @mpxr @tschoffelen Hitting the following error when transferring GitHub org.

Yeah I think you won't be able to do that directly - would you mind giving me admin access to the org instead? Then I can do the move

**Comment by ceilfors** [comment]
> > @mpxr @tschoffelen Hitting the following error when transferring GitHub org.
> 
> Yeah I think you won't be able to do that directly - would you mind giving me admin access to the org instead? Then I can do the move

Good shout, invited!

**Comment by tschoffelen** [comment]
Nice, that worked, thanks! I've moved the main repo, will figure out what to do with the examples and website repos when I have a bit more time, probably in the next few days

**Comment by ceilfors** [comment]
@tschoffelen I added you as a member of `laconia` organisation in NPM. That will allow read write permission.

<img width="513" alt="image" src="https://github.com/nearst/laconia/assets/1336981/ad7a2c1a-389b-428a-8733-604fe05bfe79">

**Comment by ceilfors** [comment]
@tschoffelen Done, only possible after you accepted!
<img width="538" alt="image" src="https://github.com/nearst/laconia/assets/1336981/945d4e70-95b9-4672-887c-e830d8a9f701">

CircleCI transfer should be automated it seems.

**Comment by tschoffelen** [comment]
Ah cool! I will set up a separate AWS env within our org to run that test soon, and probably move them to run in GitHub Actions as part of that to keep it all centralised (#916)

**Comment by ceilfors** [comment]
@tschoffelen I've initiated domain transfer out as the registrant contact change is now verified. I've sent you the transfer password, it needs to be accepted within 3 days.

**Comment by ceilfors** [comment]
@tschoffelen I've sent you the currently hosted zone details that you might need to keep the documentation website up.

The docs I'm currently following: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-migrating.html

**Comment by hugosenari** [comment]
> @mpxr @tschoffelen Hitting the following error when transferring GitHub org.

Beware of repo hijacking.

**Comment by tschoffelen** [comment]
Thanks for transferring everything over @ceilfors! 

I'm going to leave the examples and website repos in the @laconiajs org for the time being, also to give that org a reason to keep existing (so that nobody can claim `laconiajs/laconia`). 

So I think this issue might be completed, if you agree!

**Comment by ceilfors** [comment]
@tschoffelen Awesome!
